//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClientes()
        {
            this.tblTransacciones = new HashSet<tblTransacciones>();
        }
    
        public int idClientes { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string TercerApellido { get; set; }
        public Nullable<int> idSexo { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public byte[] Fotografia { get; set; }
        public Nullable<int> idOrigen { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual catOrigen catOrigen { get; set; }
        public virtual catSexo catSexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransacciones> tblTransacciones { get; set; }
        public virtual catEstados catEstados { get; set; }
    }
}
